configuration:
  swagger:
    app: 'EvoltChatApp'
    description: 'Chat Application for Evolt'
    developer: 'Tijana Burazorovic'
    email: 'tijana.burazorovic@stu.ibu.edu.ba'

spring:
  data:
    mongodb:
      uri: mongodb+srv://tijanaburazorovic:UfpkV0UvaInkF34j@cluster0.9xsfnsz.mongodb.net/?retryWrites=true&w=majority
      database: cluster0

security:
  jwt:
    secret: 'EvoltTest123hfkdkslsnjf12hdv5d25dgfjzrw46hd56dbvnd546d'

management:
  security:
    enabled: false